name: Daily ETL

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Compute DATE (UTC)
        id: set-date
        run: echo "DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Scrape
        run: python -m reddit_analysis.scraper.scrape --date "$DATE"

      - name: Score
        run: python -m reddit_analysis.inference.score --date "$DATE" --overwrite

      - name: Summarize
        run: python -m reddit_analysis.summarizer.summarize --date "$DATE" --overwrite
